### ISSUE TITLE
fail to train for unet 3D

### ISSUE THREAD

**Issue by jinxsfe** [HenriquesLab/ZeroCostDL4Mic#326]
Hi, whether adjust UNET structure for 4 depth, instead of 3 depth, and training show an error, for weight names,

ValueError Traceback (most recent call last)
in <cell line: 18>()
16 start = time.time()
17 # Start Training
---> 18 model.train(epochs=number_of_epochs,
19 batch_size=batch_size,
20 train_generator=train_generator,

1 frames
[/usr/local/lib/python3.10/dist-packages/keras/src/callbacks/model_checkpoint.py](https://localhost:8080/#) in init(self, filepath, monitor, verbose, save_best_only, save_weights_only, mode, save_freq, initial_value_threshold)
181 if save_weights_only:
182 if not self.filepath.endswith(".weights.h5"):
--> 183 raise ValueError(
184 "When using save_weights_only=True in ModelCheckpoint"
185 ", the filepath provided must end in .weights.h5 "

ValueError: When using save_weights_only=True in ModelCheckpoint, the filepath provided must end in .weights.h5 (Keras weights format). Received: filepath=/content/gdrive/MyDrive/cryo/cryo-data_processing_volume/model/gaussian4layer_320_50_0.00014/ckpt/gaussian4layer_320_50_0.00014.hdf5

I tried to change  if save_best_ckpt_only:
            ckpt_name = ckpt_dir + '/' + model_name + '.hdf5'
        else:
            ckpt_name = ckpt_dir + '/' + model_name + '_epoch_{epoch:02d}_val_loss_{val_loss:.4f}.hdf5' to if save_best_ckpt_only:
            ckpt_name = ckpt_dir + '/' + model_name + '.weights.h5'
        else:
            ckpt_name = ckpt_dir + '/' + model_name + '_epoch_{epoch:02d}_val_loss_{val_loss:.4f}.weighths.h5' or keras corresponding to the save_weight"_only = True and save best only =True requirement  but error output.
![image](https://github.com/user-attachments/assets/24b8859f-39d2-4d16-bcc8-36f406e4ce51)
I even go model check point to set these two parameter equal true and false, but also cause the same issue

**Comment by jinxsfe** [comment]
@esgomezm @paxcalpt

**Comment by jinxsfe** [comment]
I kept the original structure for your notebook but cause the same error

**Comment by jinxsfe** [comment]
![image](https://github.com/user-attachments/assets/0ae37761-d477-4b25-835f-3baf5c5b97b2)
when I change back to ckpt_name = ckpt_dir + '/' + model_name + '.hdf5'
else:
ckpt_name = ckpt_dir + '/' + model_name + 'epoch{epoch:02d}val_loss{val_loss:.4f}.hdf5'. 
![image](https://github.com/user-attachments/assets/a5bcd3a8-df2e-428e-92bb-d34006835b49)
and turn these off, it show the error
![image](https://github.com/user-attachments/assets/8809a35d-d550-4493-be65-94e26ed31847)
if I change it to keras, also show the same problem for 
![image](https://github.com/user-attachments/assets/ffa4cfd7-f8c2-453e-99b4-dd12a62416a8)

**Comment by jinxsfe** [comment]
![image](https://github.com/user-attachments/assets/c58377c4-1526-4f1e-a953-ec0b1b383e0e)
sorry I forgot to input .hdf5 but error still occur

**Comment by IvanHCenalmor** [comment]
Hi @jinxsfe,

Not 100% sure but the problem seems to be with the name of the weights. It's looking for weights ending on `.keras`, this might be a functionality of the latest Keras and TensorFlow version.

On a new version of the U-Net 3D notebook, these versions are fixed to oldest ones so this issue might not happen. 

While it's under testing the new version of the notebook it's on a different branch. You can find the updated notebook here:
[U-Net_3D_ZeroCostDL4Mic.ipynb ](https://colab.research.google.com/github/HenriquesLab/ZeroCostDL4Mic/blob/bmz_model_export_update/Colab_notebooks/U-Net_3D_ZeroCostDL4Mic.ipynb)Open In Colab

Please feel free to test it and let us know if you encounter any further issues or if this resolves the problem.

Thanks again for your valuable feedback!

Iván

**Comment by jinxsfe** [comment]
![image](https://github.com/user-attachments/assets/8f5623c3-cd12-4039-ae35-315e3b37f381)
@IvanHCenalmor , seem still missing package, even I run "!pip install imagecodecs
import imagecodecs, the error still show there

**Comment by IvanHCenalmor** [comment]
I have checked online for similar issues and I found [this one](https://stackoverflow.com/questions/65111418/python-tifffile-problems-with-loading-images-in-sagemaker) on Stack Overflow.

Seems that after you install it with `!pip install imagecodecs` you need to restart the **Restart the session** after the installation for the changes to happen.

Let me know if that works.

**Comment by jinxsfe** [comment]
I try to let old tenserflow working for 2.15 environment, but what I did is, I install tensorflow like that way for first attached images,and then run second image which can insure the tensorflow and second dependencies can be import smoothly ,then I double check the verions is matched, but when I try to use old trained(test model to predict, )which is show an error leke third images. predictions seems not working

![Image](https://github.com/user-attachments/assets/b93f5d34-61a2-4249-aa5b-06a8743825f6)

![Image](https://github.com/user-attachments/assets/fbc527a2-25d5-41c9-9f4c-b88f7b638f38)

![Image](https://github.com/user-attachments/assets/ecfcc17a-30be-4b32-b328-f02889c8f0ff)

**Comment by jinxsfe** [comment]
@IvanHCenalmor

**Comment by jinxsfe** [comment]
originally , def train(self,
              epochs,
              batch_size,
              train_generator,
              val_generator,
              model_path,
              model_name,
              optimizer='adam',
              learning_rate=0.001,
              loss='weighted_binary_crossentropy',
              metrics='dice',
              ckpt_period=1,
              save_best_ckpt_only=False,
              ckpt_path=None):

        class_weight_zero, class_weight_one = train_generator.class_weights()

        if loss == 'weighted_binary_crossentropy':
            loss = weighted_binary_crossentropy(class_weight_zero, class_weight_one)

        if metrics == 'dice':
            metrics = dice_coefficient

        if optimizer == 'adam':
            optimizer = Adam(learning_rate=learning_rate)
        elif optimizer == 'sgd':
            optimizer = SGD(learning_rate=learning_rate)
        elif optimizer == 'rmsprop':
            optimizer = RMSprop(learning_rate=learning_rate)

        self.model.compile(optimizer=optimizer,
                           loss=loss,
                           metrics=[metrics])

        if ckpt_path is not None:
            self.model.load_weights(ckpt_path)

        full_model_path = os.path.join(model_path, model_name)

        if not os.path.exists(full_model_path):
            os.makedirs(full_model_path)

        log_dir = full_model_path + '/Quality Control'

        if not os.path.exists(log_dir):
            os.makedirs(log_dir)

        ckpt_dir =  full_model_path + '/ckpt'

        if not os.path.exists(ckpt_dir):
            os.makedirs(ckpt_dir)

        csv_out_name = log_dir + '/training_evaluation.csv'
        if ckpt_path is None:
            csv_logger = CSVLogger(csv_out_name)
        else:
            csv_logger = CSVLogger(csv_out_name, append=True)

        if save_best_ckpt_only:
            ckpt_name = ckpt_dir + '/' + model_name + '.hdf5'
        else:
            ckpt_name = ckpt_dir + '/' + model_name + '_epoch_{epoch:02d}_val_loss_{val_loss:.4f}.hdf5'

        model_ckpt = ModelCheckpoint(ckpt_name,
                                     verbose=1,
                                     save_freq=ckpt_period,
                                     save_best_only=save_best_ckpt_only,
                                     save_weights_only=False)

        sample_batch, __ = val_generator.__getitem__(random.randint(0, len(val_generator)))

        sample_img = SampleImageCallback(self.model,
                                         sample_batch,
                                         model_path)

        self.model.fit(train_generator,
                       validation_data=val_generator,
                       validation_steps=math.floor(len(val_generator)/batch_size),
                       epochs=epochs,
                       callbacks=[csv_logger,
                                  model_ckpt,
                                  sample_img])

        last_ckpt_name = ckpt_dir + '/' + model_name + '_last.hdf5'
        self.model.save_weights(last_ckpt_name, save_format='tf'), for last code line,  I dont' add save_format='tf', so model weight save format is h5,  (default save fromat is self.model.save_weights(last_ckpt_name), I trainined new model and test it, new model don't have those error attached, but old have.

![Image](https://github.com/user-attachments/assets/b862721d-2e52-4718-9728-521e5a93da37)

**Comment by jinxsfe** [comment]
seems, whether I choose save format =tf or not, old predicton folder is not working

**Comment by jinxsfe** [comment]
if I training same data for the notebook. it worked, but previous saved prediction folder is not working

**Comment by jinxsfe** [comment]
Dear esgomezm:


Sorry for confusing in my problems, I describe my issue relate
https://github.com/keras-team/keras/issues/21103, and shared notebook, one
drive link in test data, prediction models, and modified notebook for
itself, I don’t modify anything apart from pip install packages, caused
newest notebook can not worked for updated package so that is why I
modified,prediction models can not worked because I trained in keras 2.12
version.

run first command line( qq tensor flow 2.15 and keras), when finished ,
restart session, and run second( the pip install packages for second
running command)all steps can be work, second is yes, I trained my data for
tensordflow2.12, and keras 2.12, which new version of notebook can not use
old ones, but we write paper and want publish in recently so old model is
important for me.


Latter I will write the problem statement for you.

**Comment by esgomezm** [comment]
Der @jinxsfe 

If notebook dependencies are modified, we cannot help. We test the notebook installations for the dependencies provided within our platform. Please, check them through [DL4MicEverywhere](https://github.com/HenriquesLab/DL4MicEverywhere) WITHOUT CHANGING ANY DEPENDENCY. If things are not working, my very strong recommendation is to retrain the model with the newest dependencies and preserving the training parameters. If the training was correct and stable, this should not provide significantly different results. 

Additionally, regarding your reported issue by email "I meet another problems in DL4MIC is that I can not connect the local or remote" please, check our documentation (including videos) [here](https://github.com/HenriquesLab/DL4MicEverywhere/blob/main/docs/REMOTE_CONNECTION.md). PLEASE FOLLOW EACH SINGLE STEP AS REPORTED AND INSTALLING ALL THE REQUIRED SOFTWARE
